#!/bin/sh

# Requires ffmpeg (audio splitting) and my `tag` wrapper script.
# This version uses the following track list format:
# startSeconds endSeconds title
# for example:
#
#0 180 Mustapha
#180 436 Fat Bottom Girls
#436 622 Jealousy
#622 809 Bicycle Race
#809 1065 If You Can't Beat Them
#1065 1246 Let Me Entertain You
#1246 1449 Dead On Time
#1449 1598 In Only Seven Days
#1598 1818 Dreamer's Ball
#1818 2028 Fun It
#2028 2221 Leaving Home Ain't Easy
#2221 2430 Don't Stop Me Now
#2430 2682 More of That Jazz

[ ! -f "$2" ] && printf "The first file should be the audio, the second should be the timecodes.\\n" && exit

echo "Enter the album/book title:"; read -r booktitle

echo "Enter the artist/author:"; read -r author

echo "Enter the publication year:"; read -r year

inputaudio="$1"

# Get a safe file name from the book.
escbook="$(echo "$booktitle" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"

! mkdir -p "$escbook" && echo "Do you have write access in this directory?" && exit 1

# As long as the extension is in the tag script, it'll work.
ext="opus"
#ext="${1#*.}"

# Get the total number of tracks from the number of lines.
total="$(wc -l < "$2")"

track=1
zeroSec="00:00:00"
while read -r x;
do
    # echo $x
    startSec="$(echo "$x" | cut -d' ' -f1)"
    endSec="$(echo "$x" | cut -d' ' -f2)"
    start="$(date -d "$zeroSec $startSec seconds" +'%H:%M:%S')"
    end="$(date -d "$zeroSec $endSec seconds" +'%H:%M:%S')"
	echo "start: " $start "  end: " $end
    title="$(echo "$x" | cut -d' ' -f 3-)"
    esctitle="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
    [ -n "$start" ] &&
    echo "From $start to $end; $track $title"
    file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
    [ -n "$start" ] && echo "Splitting \"$title\"..." && ffmpeg -nostdin -y -loglevel -8 -i "$inputaudio" -ss "$start" -to "$end" -vn "$file" &&
    echo "Tagging \"$title\"..." && tag -a "$author" -A "$booktitle" -t "$title" -n "$track" -N "$total" -d "$year" "$file"
    track="$((track+1))"
done < "$2"
