#!/bin/sh

# Requires ffmpeg (audio splitting) and my `tag` wrapper script.

[ ! -f "$2" ] && printf "The first file should be the audio, the second should be the timecodes.\\n" && exit

echo "Enter the album/book title:"; read -r booktitle

echo "Enter the artist/author:"; read -r author

echo "Enter the publication year:"; read -r year

inputaudio="$1"

# Get a safe file name from the book.
escbook="$(echo "$booktitle" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"

! mkdir -p "$escbook" && echo "Do you have write access in this directory?" && exit 1

# As long as the extension is in the tag script, it'll work.
ext="opus"
#ext="${1#*.}"

# Get the total number of tracks from the number of lines.
total="$(wc -l < "$2")"

track=1
start="00:00:00"
while read -r x;
do
    # echo $x
    duration="$(echo "$x" | cut -d' ' -f1)"
    durationM="$(echo "$duration" | cut -d':' -f1)"
    durationS="$(echo "$duration" | cut -d':' -f2)"
    # echo "duration: " $duration " durationM: " $durationM " durationS: " $durationS
    end="$(date -d "$start $durationM minutes $durationS seconds" +'%H:%M:%S')"
    # echo "start:" $start "  end:" $end
    title="$(echo "$x" | cut -d' ' -f 2-)"
    esctitle="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
    [ -n "$start" ] &&
    echo "From $start to $end; $track $title"
    file="$escbook/$(printf "%.2d" "$track")-$esctitle.$ext"
    [ -n "$start" ] && echo "Splitting \"$title\"..." && ffmpeg -nostdin -y -loglevel -8 -i "$inputaudio" -ss "$start" -to "$end" -vn "$file" &&
        echo "Tagging \"$title\"..." && tag -a "$author" -A "$booktitle" -t "$title" -n "$track" -N "$total" -d "$year" "$file"
    track="$((track+1))"
    start="$end"
done < "$2"
