#! /bin/bash

SLEEP_TIME=5   # Default time between checks.
SAFE_PERCENT=30  # Still safe at this level.
DANGER_PERCENT=29  # Warn when battery at this level.
CRITICAL_PERCENT=20  # Hibernate when battery at this level.

NAGBAR_PID=0
export DISPLAY=:0.0

function launchNagBar
{
    i3-nagbar -m 'Battery low!' -f "pango:monospace 18" -b 'Suspend!' 'systemctl suspend' >/dev/null 2>&1 &
    NAGBAR_PID=$!
}

function killNagBar
{
    if [[ $NAGBAR_PID -ne 0 ]]; then
        ps -p $NAGBAR_PID | grep "i3-nagbar"
        if [[ $? -eq 0 ]]; then
            kill $NAGBAR_PID
        fi
        NAGBAR_PID=0
    fi
}


while [ true ]; do

    killNagBar

    if [[ -n $(acpi -b | grep -i discharging) ]]; then
        rem_bat=$(acpi -b | grep -Eo "[0-9]+%" | grep -Eo "[0-9]+")

        if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
            # echo "safe"
            SLEEP_TIME=5
        else
            SLEEP_TIME=2
            if [[ $rem_bat -le $DANGER_PERCENT ]]; then
                # echo "danger"
                SLEEP_TIME=2
                launchNagBar
                notify-send "low battery!"
            fi
            if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
                # echo "critical"
                SLEEP_TIME=1
                systemctl suspend
            fi
        fi
    else
        SLEEP_TIME=10
    fi

    # echo "sleeping $SLEEP_TIME"
    sleep ${SLEEP_TIME}m

done
