#! /bin/bash

SLEEP_TIME=60   # Default time between checks. (seconds)
SAFE_PERCENT=30  # Still safe at this level.
DANGER_PERCENT=29  # Warn when battery at this level.
CRITICAL_PERCENT=20  # Hibernate when battery at this level.

NAGBAR_PID=0
export DISPLAY=:0.0

function launchNagBar
{
    i3-nagbar -m 'Battery low!' -f "pango:monospace 18" -b 'Suspend!' 'systemctl suspend' >/dev/null 2>&1 &
    NAGBAR_PID=$!
}

function killNagBar
{
    if [[ $NAGBAR_PID -ne 0 ]]; then
        ps -p $NAGBAR_PID | grep "i3-nagbar"
        if [[ $? -eq 0 ]]; then
            kill $NAGBAR_PID
        fi
        NAGBAR_PID=0
    fi
}


while [ true ]; do

    killNagBar

    acpi_text=$(acpi -b)

    if [[ -n $(echo $acpi_text | grep -i discharging) ]]; then
        rem_bat=$(echo $acpi_text | grep -Eo "[0-9]+%" | grep -Eo "[0-9]+")
        # echo $rem_bat

        if [[ $rem_bat -gt $SAFE_PERCENT ]]; then
            # echo "safe"
        else
            if [[ $rem_bat -le $DANGER_PERCENT ]]; then
                # echo "danger"
                launchNagBar
                notify-send "low battery!"
            fi
            if [[ $rem_bat -le $CRITICAL_PERCENT ]]; then
                # echo "critical"
                systemctl suspend
            fi
        fi
    fi

    # echo "sleeping $SLEEP_TIME"
    sleep ${SLEEP_TIME}s

done
