#!/bin/bash
filename="/sys/class/backlight/intel_backlight/brightness" 
x=$(cat "$filename")

if [ $1 == "u" ]
then
  if (( $x < 7422 ))
    then
    x=$(( x+390 ))
  fi
fi
if [ $1 == "d" ]
then
  if (( $x > 400 ))
    then
    x=$(( x-390 ))
  fi
fi

echo $x >"$filename" 
