#!/bin/sh
echo 'dz790pdu' > ~/dz790shutdown.txt
ssh root@dz790pdu -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790prombrok' >> ~/dz790shutdown.txt
ssh root@dz790prombrok -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790custbrok' >> ~/dz790shutdown.txt
ssh root@dz790custbrok -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790ue1' >> ~/dz790shutdown.txt
ssh root@dz790ue1 -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790health' >> ~/dz790shutdown.txt
ssh root@dz790health -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790security' >> ~/dz790shutdown.txt
ssh root@dz790security -o ConnectTimeout=10 'sudo shutdown -h now' >> ~/dz790shutdown.txt

echo 'dz790logix' >> ~/dz790shutdown.txt
net rpc shutdown -f -t 0 -U AzureUser%DZAPassword@1 -I dz790logix >> ~/dz790shutdown.txt

cat ~/dz790shutdown.txt
