#!/bin/sh
echo 'dz790pdu'
ssh root@dz790pdu -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790prombrok'
ssh root@dz790prombrok -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790custbrok'
ssh root@dz790custbrok -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790ue1'
ssh root@dz790ue1 -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790health'
ssh root@dz790health -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790security'
ssh root@dz790security -o ConnectTimeout=10 'sudo shutdown -h now' 2> /dev/null

echo 'dz790logix'
net rpc shutdown -f -t 0 -U AzureUser%DZAPassword@1 -I dz790logix
