#!/bin/sh

# cp /dev/null ~/dz790status.txt

echo -e "\ndz790pdu"
ssh root@dz790pdu -o ConnectTimeout=10 'systemctl status ams-services | grep Active' 2> /dev/null
ssh root@dz790pdu -o ConnectTimeout=10 'cd /opt/wildfly-10.0.0.Final/standalone/deployments/ && ls -1 *.war.*' 2> /dev/null  | sed 's/^/   /'

echo -e "\ndz790prombrok"
ssh root@dz790prombrok -o ConnectTimeout=10 'systemctl status ams-services | grep Active' 2> /dev/null
ssh root@dz790prombrok -o ConnectTimeout=10 'cd /opt/wildfly-10.0.0.Final/standalone/deployments/ && ls -1 *.war.*' 2> /dev/null | sed 's/^/   /'

echo -e "\ndz790custbrok"
ssh root@dz790custbrok -o ConnectTimeout=10 'systemctl status ams-services | grep Active' 2> /dev/null
ssh root@dz790custbrok -o ConnectTimeout=10 'cd /opt/wildfly-10.0.0.Final/standalone/deployments/ && ls -1 *.war.*' 2> /dev/null | sed 's/^/   /'

echo -e "\ndz790health"
ssh root@dz790health -o ConnectTimeout=10 'systemctl status ams-services | grep Active' 2> /dev/null
ssh root@dz790health -o ConnectTimeout=10 'cd /opt/wildfly-10.0.0.Final/standalone/deployments/ && ls -1 *.war.*' 2> /dev/null | sed 's/^/   /'

echo -e "\ndz790ue1"
ssh root@dz790ue1 -o ConnectTimeout=10 'systemctl status ams-services | grep Active' 2> /dev/null
ssh root@dz790ue1 -o ConnectTimeout=10 'cd /opt/wildfly-10.0.0.Final/standalone/deployments/ && ls -1 *.war.*' 2> /dev/null | sed 's/^/   /'
ssh root@dz790ue1 -o ConnectTimeout=10 'service NCRUEIOServer status | grep run' 2> /dev/null | sed 's/^/   NCRUEIOServer /'

echo -e "\ndz790security"
ssh root@dz790security -o ConnectTimeout=10 'systemctl status ams-security | grep Active' 2>/dev/null

# echo -e "\ndz790cpe1"
# ssh root@dz790cpe1 -o ConnectTimeout=10 'service tcpip_integration status | grep running' | sed 's/^/   /'

echo -e "\ndz790logix"
curl -I "dz790logix/logix/login.aspx" 2>&1 | awk '/HTTP\// {print $2}' | sed 's/^/   LogixUI response /'

#cat ~/dz790status.txt
#rm ~/dz790status.txt
