#!/bin/sh
#tsp youtube-dl -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -q --no-warnings -o '/home/chris/Downloads/ytq/%(title)s-%(id)s.%(ext)s' $1
tsp youtube-dl -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' -q -o '/home/chris/Downloads/ytq/%(title)s-%(id)s.%(ext)s' $1 2> ~/ytq.log
refresh-i3status
