#!/bin/bash
if [ -z $1 ]
then
	for f in ./*; do
		tsp ffplay "$f"
	done
else
	case $1 in
		"-h") echo "usage:"
				echo "mplay -h: show help"
				echo "mplay -l: list queue"
				echo "mplay -k: kill all"
				echo "mplay file file file...: add files to queue"
				echo "mplay: add all files to queue"
			;;
		"-l") tsp -C && tsp -l | grep -v "ID" | awk '{$1=$2=$3=$4=""; print $0}'
			;;
		"-k") tsp -K && killall ffplay
			;;
		*) 
			for f in "$@"; do
				tsp ffplay "$f"
			done
			;;
	esac
fi
