#!/bin/sh
curl -s "wttr.in/atl" >/tmp/weatherreport
sed '13q;d' /tmp/weatherreport | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print $1 "F / " $2 "F"}'
