#!/bin/bash

DATAFILE=/home/chris/Nextcloud/personal/weight.dat

now=$(date +%Y-%m-%d)
show=0

if [ ! -z $1 ]
then
	if [ $1 = "-s" ]
	then
		show=1
	else
		weight=$1
	fi
fi

if [ $show -gt 0 ]
then
	gnuplot -e "filename='$DATAFILE'" wgtplot.gpl
	exit 0
fi

if [ -z $weight ]
then
	echo Enter today\'s weight
	read weight
fi

if [ ! -e $DATAFILE ]
then
	echo "# weight data (date weight)" > $DATAFILE
fi

echo $now  $weight >> $DATAFILE

gnuplot -e "filename='$DATAFILE'" wgtplot.gpl
