#!/bin/bash

DATAFILE=/home/chris/Nextcloud/personal/weight.dat

now=$(date +%Y-%m-%d)
before=$(date --date="3 weeks ago" +%Y-%m-%d)
show=0

if [ ! -z $1 ]
then
	if [ $1 = "-s" ]
	then
		show=1
		if [ ! -z $2 ]
		then
			before=$(date --date="$2 weeks ago" +%Y-%m-%d)
		fi
	else
		weight=$1
	fi
fi

if [ $show -gt 0 ]
then
	gnuplot -p -e "set xdata time;set timefmt \"%Y-%m-%d\";set xrange [\"$before\":\"$now\"];plot \"$DATAFILE\" using 1:2 with line"
	exit 0
fi

if [ -z $weight ]
then
	echo Enter today\'s weight
	read weight
fi

if [ ! -e $DATAFILE ]
then
	echo "# weight data (date weight)" > $DATAFILE
fi

echo $now  $weight >> $DATAFILE

gnuplot -p -e "set xdata time;set timefmt \"%Y-%m-%d\";set xrange [\"$before\":\"$now\"];plot \"$DATAFILE\" using 1:2 with line"
