//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CRMConsoleAppCS.CRMWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CRMOfferConnectorSoap", Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class CRMOfferConnector : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback heartbeatOperationCompleted;
        
        private System.Threading.SendOrPostCallback postOffersEnhancedResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback postOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ackOffersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getOfferStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback aboutThisServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback postOffersImmediateOperationCompleted;
        
        private System.Threading.SendOrPostCallback transferCmOffersImmediateOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateCmToUeOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateCmToUeExOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteTranslatedOfferOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CRMOfferConnector() {
            this.Url = global::CRMConsoleAppCS.Properties.Settings.Default.CRMConsoleAppCS_CRMWebReference_CRMOfferConnector;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event heartbeatCompletedEventHandler heartbeatCompleted;
        
        /// <remarks/>
        public event postOffersEnhancedResponseCompletedEventHandler postOffersEnhancedResponseCompleted;
        
        /// <remarks/>
        public event postOffersCompletedEventHandler postOffersCompleted;
        
        /// <remarks/>
        public event getOffersCompletedEventHandler getOffersCompleted;
        
        /// <remarks/>
        public event ackOffersCompletedEventHandler ackOffersCompleted;
        
        /// <remarks/>
        public event getOfferStatusCompletedEventHandler getOfferStatusCompleted;
        
        /// <remarks/>
        public event aboutThisServiceCompletedEventHandler aboutThisServiceCompleted;
        
        /// <remarks/>
        public event postOffersImmediateCompletedEventHandler postOffersImmediateCompleted;
        
        /// <remarks/>
        public event transferCmOffersImmediateCompletedEventHandler transferCmOffersImmediateCompleted;
        
        /// <remarks/>
        public event translateCmToUeCompletedEventHandler translateCmToUeCompleted;
        
        /// <remarks/>
        public event translateCmToUeExCompletedEventHandler translateCmToUeExCompleted;
        
        /// <remarks/>
        public event deleteTranslatedOfferCompletedEventHandler deleteTranslatedOfferCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/heartbeat", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string heartbeat(ExternalInterfaceID ei) {
            object[] results = this.Invoke("heartbeat", new object[] {
                        ei});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void heartbeatAsync(ExternalInterfaceID ei) {
            this.heartbeatAsync(ei, null);
        }
        
        /// <remarks/>
        public void heartbeatAsync(ExternalInterfaceID ei, object userState) {
            if ((this.heartbeatOperationCompleted == null)) {
                this.heartbeatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnheartbeatOperationCompleted);
            }
            this.InvokeAsync("heartbeat", new object[] {
                        ei}, this.heartbeatOperationCompleted, userState);
        }
        
        private void OnheartbeatOperationCompleted(object arg) {
            if ((this.heartbeatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.heartbeatCompleted(this, new heartbeatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/postOffersEnhancedResponse", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string postOffersEnhancedResponse(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("postOffersEnhancedResponse", new object[] {
                        ei,
                        os});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void postOffersEnhancedResponseAsync(ExternalInterfaceID ei, Offers os) {
            this.postOffersEnhancedResponseAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void postOffersEnhancedResponseAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.postOffersEnhancedResponseOperationCompleted == null)) {
                this.postOffersEnhancedResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostOffersEnhancedResponseOperationCompleted);
            }
            this.InvokeAsync("postOffersEnhancedResponse", new object[] {
                        ei,
                        os}, this.postOffersEnhancedResponseOperationCompleted, userState);
        }
        
        private void OnpostOffersEnhancedResponseOperationCompleted(object arg) {
            if ((this.postOffersEnhancedResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postOffersEnhancedResponseCompleted(this, new postOffersEnhancedResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/postOffers", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool postOffers(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("postOffers", new object[] {
                        ei,
                        os});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void postOffersAsync(ExternalInterfaceID ei, Offers os) {
            this.postOffersAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void postOffersAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.postOffersOperationCompleted == null)) {
                this.postOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostOffersOperationCompleted);
            }
            this.InvokeAsync("postOffers", new object[] {
                        ei,
                        os}, this.postOffersOperationCompleted, userState);
        }
        
        private void OnpostOffersOperationCompleted(object arg) {
            if ((this.postOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postOffersCompleted(this, new postOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/getOffers", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Offers getOffers(ExternalInterfaceID ei) {
            object[] results = this.Invoke("getOffers", new object[] {
                        ei});
            return ((Offers)(results[0]));
        }
        
        /// <remarks/>
        public void getOffersAsync(ExternalInterfaceID ei) {
            this.getOffersAsync(ei, null);
        }
        
        /// <remarks/>
        public void getOffersAsync(ExternalInterfaceID ei, object userState) {
            if ((this.getOffersOperationCompleted == null)) {
                this.getOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOffersOperationCompleted);
            }
            this.InvokeAsync("getOffers", new object[] {
                        ei}, this.getOffersOperationCompleted, userState);
        }
        
        private void OngetOffersOperationCompleted(object arg) {
            if ((this.getOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOffersCompleted(this, new getOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/ackOffers", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ackOffers(ExternalInterfaceID ei, OfferList ol) {
            object[] results = this.Invoke("ackOffers", new object[] {
                        ei,
                        ol});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ackOffersAsync(ExternalInterfaceID ei, OfferList ol) {
            this.ackOffersAsync(ei, ol, null);
        }
        
        /// <remarks/>
        public void ackOffersAsync(ExternalInterfaceID ei, OfferList ol, object userState) {
            if ((this.ackOffersOperationCompleted == null)) {
                this.ackOffersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnackOffersOperationCompleted);
            }
            this.InvokeAsync("ackOffers", new object[] {
                        ei,
                        ol}, this.ackOffersOperationCompleted, userState);
        }
        
        private void OnackOffersOperationCompleted(object arg) {
            if ((this.ackOffersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ackOffersCompleted(this, new ackOffersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/getOfferStatus", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferStatuses getOfferStatus(ExternalInterfaceID ei, OfferList ol) {
            object[] results = this.Invoke("getOfferStatus", new object[] {
                        ei,
                        ol});
            return ((OfferStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void getOfferStatusAsync(ExternalInterfaceID ei, OfferList ol) {
            this.getOfferStatusAsync(ei, ol, null);
        }
        
        /// <remarks/>
        public void getOfferStatusAsync(ExternalInterfaceID ei, OfferList ol, object userState) {
            if ((this.getOfferStatusOperationCompleted == null)) {
                this.getOfferStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetOfferStatusOperationCompleted);
            }
            this.InvokeAsync("getOfferStatus", new object[] {
                        ei,
                        ol}, this.getOfferStatusOperationCompleted, userState);
        }
        
        private void OngetOfferStatusOperationCompleted(object arg) {
            if ((this.getOfferStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getOfferStatusCompleted(this, new getOfferStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/aboutThisService", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string aboutThisService() {
            object[] results = this.Invoke("aboutThisService", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void aboutThisServiceAsync() {
            this.aboutThisServiceAsync(null);
        }
        
        /// <remarks/>
        public void aboutThisServiceAsync(object userState) {
            if ((this.aboutThisServiceOperationCompleted == null)) {
                this.aboutThisServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaboutThisServiceOperationCompleted);
            }
            this.InvokeAsync("aboutThisService", new object[0], this.aboutThisServiceOperationCompleted, userState);
        }
        
        private void OnaboutThisServiceOperationCompleted(object arg) {
            if ((this.aboutThisServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.aboutThisServiceCompleted(this, new aboutThisServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/postOffersImmediate", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferImmediateStatuses postOffersImmediate(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("postOffersImmediate", new object[] {
                        ei,
                        os});
            return ((OfferImmediateStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void postOffersImmediateAsync(ExternalInterfaceID ei, Offers os) {
            this.postOffersImmediateAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void postOffersImmediateAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.postOffersImmediateOperationCompleted == null)) {
                this.postOffersImmediateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostOffersImmediateOperationCompleted);
            }
            this.InvokeAsync("postOffersImmediate", new object[] {
                        ei,
                        os}, this.postOffersImmediateOperationCompleted, userState);
        }
        
        private void OnpostOffersImmediateOperationCompleted(object arg) {
            if ((this.postOffersImmediateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postOffersImmediateCompleted(this, new postOffersImmediateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/transferCmOffersImmediate", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferImmediateStatuses transferCmOffersImmediate(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("transferCmOffersImmediate", new object[] {
                        ei,
                        os});
            return ((OfferImmediateStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void transferCmOffersImmediateAsync(ExternalInterfaceID ei, Offers os) {
            this.transferCmOffersImmediateAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void transferCmOffersImmediateAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.transferCmOffersImmediateOperationCompleted == null)) {
                this.transferCmOffersImmediateOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransferCmOffersImmediateOperationCompleted);
            }
            this.InvokeAsync("transferCmOffersImmediate", new object[] {
                        ei,
                        os}, this.transferCmOffersImmediateOperationCompleted, userState);
        }
        
        private void OntransferCmOffersImmediateOperationCompleted(object arg) {
            if ((this.transferCmOffersImmediateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transferCmOffersImmediateCompleted(this, new transferCmOffersImmediateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/translateCmToUe", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferTranslateStatuses translateCmToUe(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("translateCmToUe", new object[] {
                        ei,
                        os});
            return ((OfferTranslateStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void translateCmToUeAsync(ExternalInterfaceID ei, Offers os) {
            this.translateCmToUeAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void translateCmToUeAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.translateCmToUeOperationCompleted == null)) {
                this.translateCmToUeOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateCmToUeOperationCompleted);
            }
            this.InvokeAsync("translateCmToUe", new object[] {
                        ei,
                        os}, this.translateCmToUeOperationCompleted, userState);
        }
        
        private void OntranslateCmToUeOperationCompleted(object arg) {
            if ((this.translateCmToUeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateCmToUeCompleted(this, new translateCmToUeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/translateCmToUeEx", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferTranslateStatuses translateCmToUeEx(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("translateCmToUeEx", new object[] {
                        ei,
                        os});
            return ((OfferTranslateStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void translateCmToUeExAsync(ExternalInterfaceID ei, Offers os) {
            this.translateCmToUeExAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void translateCmToUeExAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.translateCmToUeExOperationCompleted == null)) {
                this.translateCmToUeExOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateCmToUeExOperationCompleted);
            }
            this.InvokeAsync("translateCmToUeEx", new object[] {
                        ei,
                        os}, this.translateCmToUeExOperationCompleted, userState);
        }
        
        private void OntranslateCmToUeExOperationCompleted(object arg) {
            if ((this.translateCmToUeExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateCmToUeExCompleted(this, new translateCmToUeExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.copienttech.com/CRMOfferConnector/deleteTranslatedOffer", RequestNamespace="http://www.copienttech.com/CRMOfferConnector/", ResponseNamespace="http://www.copienttech.com/CRMOfferConnector/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OfferTranslateStatuses deleteTranslatedOffer(ExternalInterfaceID ei, Offers os) {
            object[] results = this.Invoke("deleteTranslatedOffer", new object[] {
                        ei,
                        os});
            return ((OfferTranslateStatuses)(results[0]));
        }
        
        /// <remarks/>
        public void deleteTranslatedOfferAsync(ExternalInterfaceID ei, Offers os) {
            this.deleteTranslatedOfferAsync(ei, os, null);
        }
        
        /// <remarks/>
        public void deleteTranslatedOfferAsync(ExternalInterfaceID ei, Offers os, object userState) {
            if ((this.deleteTranslatedOfferOperationCompleted == null)) {
                this.deleteTranslatedOfferOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteTranslatedOfferOperationCompleted);
            }
            this.InvokeAsync("deleteTranslatedOffer", new object[] {
                        ei,
                        os}, this.deleteTranslatedOfferOperationCompleted, userState);
        }
        
        private void OndeleteTranslatedOfferOperationCompleted(object arg) {
            if ((this.deleteTranslatedOfferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteTranslatedOfferCompleted(this, new deleteTranslatedOfferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class ExternalInterfaceID {
        
        private System.Guid m_eiguidField;
        
        private int m_extInterfaceIDField;
        
        /// <remarks/>
        public System.Guid m_eiguid {
            get {
                return this.m_eiguidField;
            }
            set {
                this.m_eiguidField = value;
            }
        }
        
        /// <remarks/>
        public int m_extInterfaceID {
            get {
                return this.m_extInterfaceIDField;
            }
            set {
                this.m_extInterfaceIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferTranslateStatusStruct {
        
        private long m_cmOfferIdField;
        
        private long m_ueOfferIdField;
        
        private int m_statusField;
        
        private string m_status_msgField;
        
        /// <remarks/>
        public long m_cmOfferId {
            get {
                return this.m_cmOfferIdField;
            }
            set {
                this.m_cmOfferIdField = value;
            }
        }
        
        /// <remarks/>
        public long m_ueOfferId {
            get {
                return this.m_ueOfferIdField;
            }
            set {
                this.m_ueOfferIdField = value;
            }
        }
        
        /// <remarks/>
        public int m_status {
            get {
                return this.m_statusField;
            }
            set {
                this.m_statusField = value;
            }
        }
        
        /// <remarks/>
        public string m_status_msg {
            get {
                return this.m_status_msgField;
            }
            set {
                this.m_status_msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferTranslateStatuses {
        
        private OfferTranslateStatusStruct[] m_offerTranslateStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OfferTranslateStatusStruct[] m_offerTranslateStatuses {
            get {
                return this.m_offerTranslateStatusesField;
            }
            set {
                this.m_offerTranslateStatusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferImmediateStatusStruct {
        
        private string m_extOfferIdField;
        
        private long m_offerIdField;
        
        private int m_statusField;
        
        private string m_status_msgField;
        
        /// <remarks/>
        public string m_extOfferId {
            get {
                return this.m_extOfferIdField;
            }
            set {
                this.m_extOfferIdField = value;
            }
        }
        
        /// <remarks/>
        public long m_offerId {
            get {
                return this.m_offerIdField;
            }
            set {
                this.m_offerIdField = value;
            }
        }
        
        /// <remarks/>
        public int m_status {
            get {
                return this.m_statusField;
            }
            set {
                this.m_statusField = value;
            }
        }
        
        /// <remarks/>
        public string m_status_msg {
            get {
                return this.m_status_msgField;
            }
            set {
                this.m_status_msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferImmediateStatuses {
        
        private OfferImmediateStatusStruct[] m_offerImmediateStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OfferImmediateStatusStruct[] m_offerImmediateStatuses {
            get {
                return this.m_offerImmediateStatusesField;
            }
            set {
                this.m_offerImmediateStatusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferStatus {
        
        private string m_extOfferIdField;
        
        private int m_importedField;
        
        /// <remarks/>
        public string m_extOfferId {
            get {
                return this.m_extOfferIdField;
            }
            set {
                this.m_extOfferIdField = value;
            }
        }
        
        /// <remarks/>
        public int m_imported {
            get {
                return this.m_importedField;
            }
            set {
                this.m_importedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferStatuses {
        
        private OfferStatus[] m_offerImportStatusesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OfferStatus[] m_offerImportStatuses {
            get {
                return this.m_offerImportStatusesField;
            }
            set {
                this.m_offerImportStatusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferMapping {
        
        private long m_offerIDField;
        
        private string m_extOfferIDField;
        
        private string m_filenameField;
        
        /// <remarks/>
        public long m_offerID {
            get {
                return this.m_offerIDField;
            }
            set {
                this.m_offerIDField = value;
            }
        }
        
        /// <remarks/>
        public string m_extOfferID {
            get {
                return this.m_extOfferIDField;
            }
            set {
                this.m_extOfferIDField = value;
            }
        }
        
        /// <remarks/>
        public string m_filename {
            get {
                return this.m_filenameField;
            }
            set {
                this.m_filenameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferList {
        
        private OfferMapping[] m_offersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OfferMapping[] m_offers {
            get {
                return this.m_offersField;
            }
            set {
                this.m_offersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class EncapsulatedXML {
        
        private string m_encoded_xmlField;
        
        /// <remarks/>
        public string m_encoded_xml {
            get {
                return this.m_encoded_xmlField;
            }
            set {
                this.m_encoded_xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class OfferDefinition {
        
        private long m_offerIDField;
        
        private string m_extOfferIDField;
        
        private string m_filenameField;
        
        private EncapsulatedXML m_offerXMLField;
        
        private int m_engineIDField;
        
        private string m_locationsField;
        
        /// <remarks/>
        public long m_offerID {
            get {
                return this.m_offerIDField;
            }
            set {
                this.m_offerIDField = value;
            }
        }
        
        /// <remarks/>
        public string m_extOfferID {
            get {
                return this.m_extOfferIDField;
            }
            set {
                this.m_extOfferIDField = value;
            }
        }
        
        /// <remarks/>
        public string m_filename {
            get {
                return this.m_filenameField;
            }
            set {
                this.m_filenameField = value;
            }
        }
        
        /// <remarks/>
        public EncapsulatedXML m_offerXML {
            get {
                return this.m_offerXMLField;
            }
            set {
                this.m_offerXMLField = value;
            }
        }
        
        /// <remarks/>
        public int m_engineID {
            get {
                return this.m_engineIDField;
            }
            set {
                this.m_engineIDField = value;
            }
        }
        
        /// <remarks/>
        public string m_locations {
            get {
                return this.m_locationsField;
            }
            set {
                this.m_locationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.copienttech.com/CRMOfferConnector/")]
    public partial class Offers {
        
        private OfferDefinition[] m_offersField;
        
        /// <remarks/>
        public OfferDefinition[] m_offers {
            get {
                return this.m_offersField;
            }
            set {
                this.m_offersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void heartbeatCompletedEventHandler(object sender, heartbeatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class heartbeatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal heartbeatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void postOffersEnhancedResponseCompletedEventHandler(object sender, postOffersEnhancedResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postOffersEnhancedResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postOffersEnhancedResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void postOffersCompletedEventHandler(object sender, postOffersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getOffersCompletedEventHandler(object sender, getOffersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Offers Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Offers)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ackOffersCompletedEventHandler(object sender, ackOffersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ackOffersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ackOffersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getOfferStatusCompletedEventHandler(object sender, getOfferStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getOfferStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getOfferStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferStatuses)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void aboutThisServiceCompletedEventHandler(object sender, aboutThisServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class aboutThisServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal aboutThisServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void postOffersImmediateCompletedEventHandler(object sender, postOffersImmediateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postOffersImmediateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postOffersImmediateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferImmediateStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferImmediateStatuses)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void transferCmOffersImmediateCompletedEventHandler(object sender, transferCmOffersImmediateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transferCmOffersImmediateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transferCmOffersImmediateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferImmediateStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferImmediateStatuses)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void translateCmToUeCompletedEventHandler(object sender, translateCmToUeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateCmToUeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateCmToUeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferTranslateStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferTranslateStatuses)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void translateCmToUeExCompletedEventHandler(object sender, translateCmToUeExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateCmToUeExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateCmToUeExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferTranslateStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferTranslateStatuses)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void deleteTranslatedOfferCompletedEventHandler(object sender, deleteTranslatedOfferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteTranslatedOfferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteTranslatedOfferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OfferTranslateStatuses Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OfferTranslateStatuses)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591